

images:
	inkscape -z -e eurobet-logo.png -w 31 -h 31 eurobet-logo.svg
	inkscape -z -e eurobet-logo@2x.png -w 62 -h 62 eurobet-logo.svg
	inkscape -z -e eurobet-logo@3x.png -w 93 -h 93 eurobet-logo.svg
	inkscape -z -e eurobet-logo-big.png -w 256 -h 59 eurobet-logo-big.svg
	inkscape -z -e eurobet-logo-big@2x.png -w 512 -h 119 eurobet-logo-big.svg
	inkscape -z -e eurobet-logo-big@3x.png -w 768 -h 178 eurobet-logo-big.svg
	inkscape -z -e ball.png -w 50 -h 50 ball.svg
	inkscape -z -e ball@2x.png -w 100 -h 100 ball.svg
	inkscape -z -e ball@3x.png -w 150 -h 150 ball.svg
	inkscape -z -e grass.png -w 360 -h 185 grass.svg
	inkscape -z -e grass@2x.png -w 720 -h 370 grass.svg
	inkscape -z -e grass@3x.png -w 1080 -h 555 grass.svg
